apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      securityContext:
        runAsNonRoot: true          # Ensures the pod is not running as root
        fsGroup: 2000               # Set the group ID for file access (optional, adjust as necessary)
      containers:
        - name: webapp-container
          image: thumunavyasri/fastapi-docker-app:b64a844dcae329f985b7ecc033d68d407f819ddf
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: 250m
              memory: 400Mi
            limits:
              cpu: 500m
              memory: 800Mi
          securityContext:
            runAsUser: 1000             # Ensures the container runs as user with UID 1000 (non-root)
            allowPrivilegeEscalation: false  # Prevents escalation of privileges (security best practice)
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30007

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: webapp-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app-deployment
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70
