name: Deploy to EC2

on:
  push:
    branches: ["feature/githubactions"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
            docker pull thumunavyasri/fastapi-docker-app:latest
            docker stop fastapi-docker-app || true
            docker rm fastapi-docker-app || true
            docker run -d -p 8000:8000 --name fastapi-docker-app thumunavyasri/fastapi-docker-app:latest
